name: ci
on:
  pull_request:
  push:
    branches: [ main ]
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check shell scripts
        uses: ludeeus/action-shellcheck@2.0.0
        with:
          scandir: .
